project_name: rode-collector-sonarqube
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - "ghcr.io/rode/collector-sonarqube:latest"
      - "ghcr.io/rode/collector-sonarqube:{{ .Tag }}"
      - "ghcr.io/rode/collector-sonarqube:v{{ .Major }}"
      - "ghcr.io/rode/collector-sonarqube:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "main.go"
      - "config"
      - "listener"
      - "sonar"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
